### ISSUE TITLE
npm Backend Producation Error

### ISSUE THREAD

**Issue by AnasSharif** [hrshadhin/school-management-system#52]
When i run `npm backend-prod` the below error show in terminal
`TypeError: dep.getResourceIdentifier is not a function
    at addDependency (/home/anas/NetBeansProjects/school-management-systems/node_modules/webpack/lib/Compilation.js:690:30)
    at iterationOfArrayCallback (/home/anas/NetBeansProjects/school-management-systems/node_modules/webpack/lib/Compilation.js:194:3)
    at addDependenciesBlock (/home/anas/NetBeansProjects/school-management-systems/node_modules/webpack/lib/Compilation.js:712:5)
    at Compilation.processModuleDependencies (/home/anas/NetBeansProjects/school-management-systems/node_modules/webpack/lib/Compilation.js:723:4)
    at afterBuild (/home/anas/NetBeansProjects/school-management-systems/node_modules/webpack/lib/Compilation.js:855:15)
    at buildModule.err (/home/anas/NetBeansProjects/school-management-systems/node_modules/webpack/lib/Compilation.js:899:11)
    at callback (/home/anas/NetBeansProjects/school-management-systems/node_modules/webpack/lib/Compilation.js:628:5)
    at module.build.error (/home/anas/NetBeansProjects/school-management-systems/node_modules/webpack/lib/Compilation.js:676:12)
    at handleParseResult (/home/anas/NetBeansProjects/school-management-systems/node_modules/webpack/lib/NormalModule.js:456:12)
    at doBuild.err (/home/anas/NetBeansProjects/school-management-systems/node_modules/webpack/lib/NormalModule.js:478:6)
    at runLoaders (/home/anas/NetBeansProjects/school-management-systems/node_modules/webpack/lib/NormalModule.js:342:12)
    at /home/anas/NetBeansProjects/school-management-systems/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/home/anas/NetBeansProjects/school-management-systems/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at Array.<anonymous> (/home/anas/NetBeansProjects/school-management-systems/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/home/anas/NetBeansProjects/school-management-systems/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/home/anas/NetBeansProjects/school-management-systems/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /home/anas/NetBeansProjects/school-management-systems/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ backend-production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js --env.mixfile=webpack.backend.mix.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ backend-production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/anas/.npm/_logs/2019-01-03T18_01_38_949Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ backend-prod: `npm run backend-production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ backend-prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/anas/.npm/_logs/2019-01-03T18_01_39_208Z-debug.log
`
**My package.json**
`{
  "private": true,
  "scripts": {
    "prefrontend-dev": "rm -rf public/frontend",
    "frontend-dev": "npm run frontend-development",
    "frontend-development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js --env.mixfile=webpack.frontend.mix.js",
    "frontend-watch": "npm run frontend-development -- --watch",
    "frontend-prod": "npm run frontend-production",
    "frontend-production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js --env.mixfile=webpack.frontend.mix.js",
    "prebackend-dev": "rm -rf public/css public/js public/fonts public/images",
    "backend-dev": "npm run backend-development",
    "backend-development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js --env.mixfile=webpack.backend.mix.js",
    "backend-watch": "npm run backend-development -- --watch",
    "backend-prod": "npm run backend-production",
    "backend-production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js --env.mixfile=webpack.backend.mix.js"
  },
  "devDependencies": {
    "axios": "^0.18",
    "browser-sync": "^2.26.3",
    "browser-sync-webpack-plugin": "^2.2.2",
    "cross-env": "^5.2.0",
    "laravel-mix": "^2.1.14",
    "lodash": "^4.17.11",
    "purify-css": "^1.2.5",
    "purifycss-webpack": "^0.7.0",
    "script-loader": "^0.7.2",
    "webpack": "^4.28.3",
    "webpack-cli": "^3.1.2"
  },
  "dependencies": {
    "@webpack-cli/init": "^0.1.2",
    "bootstrap": "^3.3.7",
    "bootstrap-datepicker": "^1.7.0",
    "bootstrap-daterangepicker": "^2.1.25",
    "chart.js": "^2.7.3",
    "datatables.net": "^1.10.15",
    "datatables.net-bs": "^1.10.15",
    "datatables.net-buttons": "^1.5.3",
    "datatables.net-responsive-bs": "^2.2.1",
    "fastclick": "^1.0.6",
    "font-awesome": "^4.7.0",
    "fs": "0.0.1-security",
    "fullcalendar": "^3.9.0",
    "icheck": "^1.0.2",
    "inputmask": "^3.3.7",
    "install": "^0.11.0",
    "jquery": "^3.3.1",
    "jquery-ui": "^1.12.1",
    "jquery-validation": "^1.17.0",
    "jszip": "^3.1.5",
    "moment": "^2.18.1",
    "pdfmake": "^0.1.39",
    "popper.js": "^1.14.5",
    "remove": "^0.1.5",
    "select2": "^4.0.3",
    "slimscroll": "^0.9.1",
    "sweetalert2": "^7.29.0",
    "toastr": "^2.1.4"
  }
}
`

**Comment by hrshadhin** [comment]
Problem with NPM, check full log here `/home/anas/.npm/_logs/2019-01-03T18_01_38_949Z-debug.log` and find solutions on google.
